// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicCreateStep,
  DefaultCreateStepProps,
} from "./plasmic/xrpense/PlasmicCreateStep";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface CreateStepProps extends Omit<DefaultCreateStepProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultCreateStepProps altogether and have
// total control over the props for your component.
export interface CreateStepProps extends DefaultCreateStepProps {}

function CreateStep_(props: CreateStepProps, ref: HTMLElementRefOf<"div">) {
  // Use PlasmicCreateStep to render this component as it was

  // Props you can pass into PlasmicCreateStep are:

  // By default, we are just piping all CreateStepProps here, but feel free
  // to do whatever works for you.

  return <PlasmicCreateStep root={{ ref }} {...props} />;
}

const CreateStep = React.forwardRef(CreateStep_);
export default CreateStep;
