// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicIconButton,
  DefaultIconButtonProps,
} from "./plasmic/xrpense/PlasmicIconButton";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface IconButtonProps extends Omit<DefaultIconButtonProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultIconButtonProps altogether and have
// total control over the props for your component.
export interface IconButtonProps extends DefaultIconButtonProps {}

function IconButton_(props: IconButtonProps, ref: HTMLElementRefOf<"a">) {
  // Use PlasmicIconButton to render this component as it was

  // Props you can pass into PlasmicIconButton are:

  // By default, we are just piping all IconButtonProps here, but feel free
  // to do whatever works for you.

  return <PlasmicIconButton root={{ ref }} {...props} />;
}

const IconButton = React.forwardRef(IconButton_);
export default IconButton;
