// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicInboxItem,
  DefaultInboxItemProps,
} from "./plasmic/xrpense/PlasmicInboxItem";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface InboxItemProps extends Omit<DefaultInboxItemProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultInboxItemProps altogether and have
// total control over the props for your component.
export interface InboxItemProps extends DefaultInboxItemProps {}

function InboxItem_(props: InboxItemProps, ref: HTMLElementRefOf<"a">) {
  // Use PlasmicInboxItem to render this component as it was

  // Props you can pass into PlasmicInboxItem are:

  // By default, we are just piping all InboxItemProps here, but feel free
  // to do whatever works for you.

  return <PlasmicInboxItem root={{ ref }} {...props} />;
}

const InboxItem = React.forwardRef(InboxItem_);
export default InboxItem;
