// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicLayoutBase,
  DefaultLayoutBaseProps,
} from "./plasmic/xrpense/PlasmicLayoutBase";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface LayoutBaseProps extends Omit<DefaultLayoutBaseProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultLayoutBaseProps altogether and have
// total control over the props for your component.
export interface LayoutBaseProps extends DefaultLayoutBaseProps {}

function LayoutBase(props: LayoutBaseProps) {
  // Use PlasmicLayoutBase to render this component as it was

  // Props you can pass into PlasmicLayoutBase are:

  // By default, we are just piping all LayoutBaseProps here, but feel free
  // to do whatever works for you.

  return <PlasmicLayoutBase {...props} />;
}

export default LayoutBase;
