// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicLayout,
  DefaultLayoutProps,
} from "./plasmic/xrpense/PlasmicLayout";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface LayoutProps extends Omit<DefaultLayoutProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultLayoutProps altogether and have
// total control over the props for your component.
export interface LayoutProps extends DefaultLayoutProps {}

function Layout(props: LayoutProps) {
  // Use PlasmicLayout to render this component as it was

  // Props you can pass into PlasmicLayout are:

  // By default, we are just piping all LayoutProps here, but feel free
  // to do whatever works for you.

  return <PlasmicLayout {...props} />;
}

export default Layout;
