// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicReqItem,
  DefaultReqItemProps,
} from "./plasmic/xrpense/PlasmicReqItem";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface ReqItemProps extends Omit<DefaultReqItemProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultReqItemProps altogether and have
// total control over the props for your component.
export interface ReqItemProps extends DefaultReqItemProps {}

function ReqItem_(props: ReqItemProps, ref: HTMLElementRefOf<"a">) {
  // Use PlasmicReqItem to render this component as it was

  // Props you can pass into PlasmicReqItem are:

  // By default, we are just piping all ReqItemProps here, but feel free
  // to do whatever works for you.

  return <PlasmicReqItem root={{ ref }} {...props} />;
}

const ReqItem = React.forwardRef(ReqItem_);
export default ReqItem;
