// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicSelectButton,
  DefaultSelectButtonProps,
} from "./plasmic/xrpense/PlasmicSelectButton";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface SelectButtonProps extends Omit<DefaultSelectButtonProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultSelectButtonProps altogether and have
// total control over the props for your component.
export interface SelectButtonProps extends DefaultSelectButtonProps {}

function SelectButton_(props: SelectButtonProps, ref: HTMLElementRefOf<"a">) {
  // Use PlasmicSelectButton to render this component as it was

  // Props you can pass into PlasmicSelectButton are:

  // By default, we are just piping all SelectButtonProps here, but feel free
  // to do whatever works for you.

  return <PlasmicSelectButton root={{ ref }} {...props} />;
}

const SelectButton = React.forwardRef(SelectButton_);
export default SelectButton;
