// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4QmempJ4uAWNpTRouKWPHf
// Component: h2Cqfb2WKnuT

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_xrpense.module.css"; // plasmic-import: 4QmempJ4uAWNpTRouKWPHf/projectcss
import sty from "./PlasmicReqItem.module.css"; // plasmic-import: h2Cqfb2WKnuT/css

import CompleteIcon from "./icons/PlasmicIcon__Complete"; // plasmic-import: pTJFuCWk8NGr/icon
import ThreedotsSvgrepoComsvgIcon from "./icons/PlasmicIcon__ThreedotsSvgrepoComsvg"; // plasmic-import: wN9HcmYrq_HW/icon
import Error16SvgrepoComsvgIcon from "./icons/PlasmicIcon__Error16SvgrepoComsvg"; // plasmic-import: dD3ugMsUg3e6/icon
import HandShakeSvgrepoComsvgIcon from "./icons/PlasmicIcon__HandShakeSvgrepoComsvg"; // plasmic-import: uL_WO8lUTM0O/icon

createPlasmicElementProxy;

export type PlasmicReqItem__VariantMembers = {
  type: "paid" | "inReview" | "rejected" | "unpaid";
  unread: "unread";
};
export type PlasmicReqItem__VariantsArgs = {
  type?: MultiChoiceArg<"paid" | "inReview" | "rejected" | "unpaid">;
  unread?: SingleBooleanChoiceArg<"unread">;
};
type VariantPropType = keyof PlasmicReqItem__VariantsArgs;
export const PlasmicReqItem__VariantProps = new Array<VariantPropType>(
  "type",
  "unread"
);

export type PlasmicReqItem__ArgsType = {
  unixtime?: number;
  title?: React.ReactNode;
  bill?: React.ReactNode;
  reqId?: string;
  amount?: React.ReactNode;
  date?: React.ReactNode;
};
type ArgPropType = keyof PlasmicReqItem__ArgsType;
export const PlasmicReqItem__ArgProps = new Array<ArgPropType>(
  "unixtime",
  "title",
  "bill",
  "reqId",
  "amount",
  "date"
);

export type PlasmicReqItem__OverridesType = {
  root?: p.Flex<"a"> & Partial<LinkProps>;
  svg?: p.Flex<"svg">;
};

export interface DefaultReqItemProps {
  unixtime?: number;
  title?: React.ReactNode;
  bill?: React.ReactNode;
  reqId?: string;
  amount?: React.ReactNode;
  date?: React.ReactNode;
  type?: MultiChoiceArg<"paid" | "inReview" | "rejected" | "unpaid">;
  unread?: SingleBooleanChoiceArg<"unread">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicReqItem__RenderFunc(props: {
  variants: PlasmicReqItem__VariantsArgs;
  args: PlasmicReqItem__ArgsType;
  overrides: PlasmicReqItem__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          unixtime: 10000000
        },
        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof p.useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "type",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.type
      },
      {
        path: "unread",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.unread
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <p.Stack
      as={p.PlasmicLink}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.a,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root,
        {
          [sty.roottype_inReview]: hasVariant($state, "type", "inReview"),
          [sty.roottype_paid]: hasVariant($state, "type", "paid"),
          [sty.roottype_rejected]: hasVariant($state, "type", "rejected"),
          [sty.roottype_unpaid]: hasVariant($state, "type", "unpaid"),
          [sty.rootunread]: hasVariant($state, "unread", "unread")
        }
      )}
      component={Link}
      href={`/inbox/${(() => {
        try {
          return $props.reqId;
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return undefined;
          }
          throw e;
        }
      })()}`}
      platform={"nextjs"}
    >
      <p.PlasmicIcon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        PlasmicIconType={
          hasVariant($state, "type", "unpaid")
            ? HandShakeSvgrepoComsvgIcon
            : hasVariant($state, "type", "rejected")
            ? Error16SvgrepoComsvgIcon
            : hasVariant($state, "type", "inReview")
            ? ThreedotsSvgrepoComsvgIcon
            : CompleteIcon
        }
        className={classNames(projectcss.all, sty.svg, {
          [sty.svgtype_inReview]: hasVariant($state, "type", "inReview"),
          [sty.svgtype_rejected]: hasVariant($state, "type", "rejected"),
          [sty.svgtype_unpaid]: hasVariant($state, "type", "unpaid"),
          [sty.svgunread]: hasVariant($state, "unread", "unread")
        })}
        role={"img"}
      />

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__yp2Iq)}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__hyvOi)}
        >
          <div
            className={classNames(projectcss.all, sty.freeBox__yKdzC, {
              [sty.freeBoxunread__yKdzCuqwna]: hasVariant(
                $state,
                "unread",
                "unread"
              )
            })}
          >
            {p.renderPlasmicSlot({
              defaultContents: "\u30bf\u30a4\u30c8\u30eb",
              value: args.title,
              className: classNames(sty.slotTargetTitle, {
                [sty.slotTargetTitletype_paid]: hasVariant(
                  $state,
                  "type",
                  "paid"
                ),
                [sty.slotTargetTitleunread]: hasVariant(
                  $state,
                  "unread",
                  "unread"
                )
              })
            })}
          </div>
          {p.renderPlasmicSlot({
            defaultContents: "2023/12/7",
            value: args.date,
            className: classNames(sty.slotTargetDate, {
              [sty.slotTargetDatetype_paid]: hasVariant($state, "type", "paid"),
              [sty.slotTargetDateunread]: hasVariant($state, "unread", "unread")
            })
          })}
        </p.Stack>
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__gcF2R, {
            [sty.freeBoxtype_paid__gcF2R0MG7H]: hasVariant(
              $state,
              "type",
              "paid"
            )
          })}
        >
          {p.renderPlasmicSlot({
            defaultContents: "\u682a\u5f0f\u4f1a\u793eXX",
            value: args.bill,
            className: classNames(sty.slotTargetBill)
          })}
          {p.renderPlasmicSlot({
            defaultContents: "\uffe55000",
            value: args.amount,
            className: classNames(sty.slotTargetAmount, {
              [sty.slotTargetAmounttype_paid]: hasVariant(
                $state,
                "type",
                "paid"
              )
            })
          })}
        </p.Stack>
      </p.Stack>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "a";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicReqItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicReqItem__VariantsArgs;
    args?: PlasmicReqItem__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicReqItem__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicReqItem__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicReqItem__ArgProps,
          internalVariantPropNames: PlasmicReqItem__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicReqItem__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicReqItem";
  } else {
    func.displayName = `PlasmicReqItem.${nodeName}`;
  }
  return func;
}

export const PlasmicReqItem = Object.assign(
  // Top-level PlasmicReqItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicReqItem
    internalVariantProps: PlasmicReqItem__VariantProps,
    internalArgProps: PlasmicReqItem__ArgProps
  }
);

export default PlasmicReqItem;
/* prettier-ignore-end */
