// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4QmempJ4uAWNpTRouKWPHf
// Component: g7edmX0VglfL

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import LayoutBase from "../../LayoutBase"; // plasmic-import: xHlJ0wygH-6y/component
import CreateStep from "../../CreateStep"; // plasmic-import: 0Id__lT8w_bK/component
import SelectButton from "../../SelectButton"; // plasmic-import: BWLrUxpptVrX/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_xrpense.module.css"; // plasmic-import: 4QmempJ4uAWNpTRouKWPHf/projectcss
import sty from "./PlasmicCreateTemplateSelect.module.css"; // plasmic-import: g7edmX0VglfL/css

createPlasmicElementProxy;

export type PlasmicCreateTemplateSelect__VariantMembers = {};
export type PlasmicCreateTemplateSelect__VariantsArgs = {};
type VariantPropType = keyof PlasmicCreateTemplateSelect__VariantsArgs;
export const PlasmicCreateTemplateSelect__VariantProps =
  new Array<VariantPropType>();

export type PlasmicCreateTemplateSelect__ArgsType = {};
type ArgPropType = keyof PlasmicCreateTemplateSelect__ArgsType;
export const PlasmicCreateTemplateSelect__ArgProps = new Array<ArgPropType>();

export type PlasmicCreateTemplateSelect__OverridesType = {
  root?: p.Flex<"div">;
  layoutBase?: p.Flex<typeof LayoutBase>;
  createStep?: p.Flex<typeof CreateStep>;
  section?: p.Flex<"section">;
  text?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultCreateTemplateSelectProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCreateTemplateSelect__RenderFunc(props: {
  variants: PlasmicCreateTemplateSelect__VariantsArgs;
  args: PlasmicCreateTemplateSelect__ArgsType;
  overrides: PlasmicCreateTemplateSelect__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <LayoutBase
            data-plasmic-name={"layoutBase"}
            data-plasmic-override={overrides.layoutBase}
            className={classNames("__wab_instance", sty.layoutBase)}
          >
            <CreateStep
              data-plasmic-name={"createStep"}
              data-plasmic-override={overrides.createStep}
              className={classNames("__wab_instance", sty.createStep)}
              currentStep={1}
            />

            <section
              data-plasmic-name={"section"}
              data-plasmic-override={overrides.section}
              className={classNames(projectcss.all, sty.section)}
            >
              <div
                data-plasmic-name={"text"}
                data-plasmic-override={overrides.text}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text
                )}
              >
                {
                  "\u7533\u8acb\u3059\u308b\u7d4c\u8cbb\u3092\u9078\u629e\u3057\u3066\u304f\u3060\u3055\u3044"
                }
              </div>
              <p.Stack
                as={"div"}
                data-plasmic-name={"freeBox"}
                data-plasmic-override={overrides.freeBox}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox)}
              >
                <SelectButton
                  className={classNames(
                    "__wab_instance",
                    sty.selectButton__kl6Vk
                  )}
                  to={"/create/detail?type=travel"}
                >
                  {"\u4ea4\u901a\u8cbb"}
                </SelectButton>
                <SelectButton
                  className={classNames(
                    "__wab_instance",
                    sty.selectButton__btzpy
                  )}
                  to={"/create/detail?type=convention"}
                >
                  {"\u4f1a\u8b70\u8cbb"}
                </SelectButton>
                <SelectButton
                  className={classNames(
                    "__wab_instance",
                    sty.selectButton__vtEqn
                  )}
                  to={"/create/detail?type=consumable"}
                >
                  {"\u6d88\u8017\u54c1\u8cbb"}
                </SelectButton>
              </p.Stack>
            </section>
          </LayoutBase>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "layoutBase", "createStep", "section", "text", "freeBox"],
  layoutBase: ["layoutBase", "createStep", "section", "text", "freeBox"],
  createStep: ["createStep"],
  section: ["section", "text", "freeBox"],
  text: ["text"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  layoutBase: typeof LayoutBase;
  createStep: typeof CreateStep;
  section: "section";
  text: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCreateTemplateSelect__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCreateTemplateSelect__VariantsArgs;
    args?: PlasmicCreateTemplateSelect__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCreateTemplateSelect__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicCreateTemplateSelect__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCreateTemplateSelect__ArgProps,
          internalVariantPropNames: PlasmicCreateTemplateSelect__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCreateTemplateSelect__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCreateTemplateSelect";
  } else {
    func.displayName = `PlasmicCreateTemplateSelect.${nodeName}`;
  }
  return func;
}

export const PlasmicCreateTemplateSelect = Object.assign(
  // Top-level PlasmicCreateTemplateSelect renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    layoutBase: makeNodeComponent("layoutBase"),
    createStep: makeNodeComponent("createStep"),
    section: makeNodeComponent("section"),
    text: makeNodeComponent("text"),
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicCreateTemplateSelect
    internalVariantProps: PlasmicCreateTemplateSelect__VariantProps,
    internalArgProps: PlasmicCreateTemplateSelect__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicCreateTemplateSelect;
/* prettier-ignore-end */
