// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4QmempJ4uAWNpTRouKWPHf
// Component: 0Id__lT8w_bK

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Step from "../../Step"; // plasmic-import: 7s6wc0JQ2YJz/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_xrpense.module.css"; // plasmic-import: 4QmempJ4uAWNpTRouKWPHf/projectcss
import sty from "./PlasmicCreateStep.module.css"; // plasmic-import: 0Id__lT8w_bK/css

createPlasmicElementProxy;

export type PlasmicCreateStep__VariantMembers = {};
export type PlasmicCreateStep__VariantsArgs = {};
type VariantPropType = keyof PlasmicCreateStep__VariantsArgs;
export const PlasmicCreateStep__VariantProps = new Array<VariantPropType>();

export type PlasmicCreateStep__ArgsType = {
  currentStep?: number;
};
type ArgPropType = keyof PlasmicCreateStep__ArgsType;
export const PlasmicCreateStep__ArgProps = new Array<ArgPropType>(
  "currentStep"
);

export type PlasmicCreateStep__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultCreateStepProps {
  currentStep?: number;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCreateStep__RenderFunc(props: {
  variants: PlasmicCreateStep__VariantsArgs;
  args: PlasmicCreateStep__ArgsType;
  overrides: PlasmicCreateStep__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <Step
          active={(() => {
            try {
              return $props.currentStep == 1;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()}
          className={classNames("__wab_instance", sty.step__xbjjC)}
          step={1}
        >
          {"\u7533\u8acb\u3059\u308b\u7d4c\u8cbb\u3092\u9078\u629e\u3059\u308b"}
        </Step>
        <Step
          active={(() => {
            try {
              return $props.currentStep == 2;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()}
          className={classNames("__wab_instance", sty.step__p8Rmu)}
          step={2}
        >
          {"\u7d4c\u8cbb\u7533\u8acb\u3092\u884c\u3046"}
        </Step>
        <Step
          active={(() => {
            try {
              return $props.currentStep == 3;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()}
          className={classNames("__wab_instance", sty.step__mNjZm)}
          step={3}
        >
          {"\u7533\u8acb\u5185\u5bb9\u78ba\u8a8d"}
        </Step>
        <Step
          active={(() => {
            try {
              return $props.currentStep == 4;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return [];
              }
              throw e;
            }
          })()}
          className={classNames("__wab_instance", sty.step__b0I40)}
          step={4}
        >
          {"\u5b8c\u4e86"}
        </Step>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCreateStep__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCreateStep__VariantsArgs;
    args?: PlasmicCreateStep__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCreateStep__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicCreateStep__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCreateStep__ArgProps,
          internalVariantPropNames: PlasmicCreateStep__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCreateStep__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCreateStep";
  } else {
    func.displayName = `PlasmicCreateStep.${nodeName}`;
  }
  return func;
}

export const PlasmicCreateStep = Object.assign(
  // Top-level PlasmicCreateStep renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicCreateStep
    internalVariantProps: PlasmicCreateStep__VariantProps,
    internalArgProps: PlasmicCreateStep__ArgProps
  }
);

export default PlasmicCreateStep;
/* prettier-ignore-end */
