---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xrpense-fe-deployment
  namespace: aokiapp-xrpense
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: github-registry-secret
      containers:
        - name: frontend-container
          image: frontend
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: xrpense-fe-service
  namespace: aokiapp-xrpense
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xrpense-fe-ingress
  namespace: aokiapp-xrpense
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt"
  labels:
    app: frontend
spec:
  ingressClassName: traefik
  rules:
    - host: xrpense.kintaman.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: xrpense-fe-service
                port:
                  number: 80
